fasta = "TAATTTTAAACTTAATAAATTTATAATTTTATCTTTTATTATTAATTTTATAATTTTTTTATATTTAAATTTTAAATTAAATTTATTTTACTCATTAATTAAAAAATATAATTTTTCCGAATCTAATTATTTAATAAAACTTAATGAAATAAATTTTCAAAATATTTTATATTTATATGAATACCCATTGAATAATATCACCATTAGATCAATATTTTACTTATTGATTTCTATATTTTCTATTATTAAAATCTGTTCTATAAAATCTATCTCCATACGTAAAATCAATTAATTAACCCTTAATATTAAATAACAATTATGAATAAAAATTTAATTAATTTTATAAAAATATCTATAATGAATCTACCCTCACCTGTGAATATTTCATACTTATGAAATTTTGGATCTTTACTTGGATTATTTCTAATAATTCAAATTATAAGAGGATTCTTTTTATCTATACACTATTGCCCCAACACAAATTTTGCTTTTTTTAGAATTATTCACATCATTCAAAATGTAAAAATAGGATGATTAATTCATAATATTCATATTAATGGAGCTTCAATATTTTTTATTTGTATATATTTACATATCAGACGAGGATTATATTATAATTCATATAAATTAATTAATACTTGATTAATTGGAGTATCAATTTATCTTCTATCAATAGCTACTGCTTTTTTAGGTTATGTACTTCCTTGAGGACAAATATCATTCTGAGGAGCAACTGTTATTACTAATTTAATATCTACAATTCCTTATATGGAAACTTAATAGTACAATGAATCTGAGGAGGATTTTCAATTAATAACGCTACATTAAATCGATTTTATTCAATCCATTTTATTCTTCCATTTATTATTACAATAATAGTAATATTACATTTATTTTTTTTACATACCACAGGCTCATCAAACCCATTAGGAATTAATAGAAATTTATATAAAATTCCTTTTCATATCTATTTTTCAATTAAAGATATTTTAGGGTTCATAATTTTTATTTTTTTTTTCTGATTAATCAATCTTGAATACCCATATATTTTTAGAGATCCAGATAATTTTATTCCAGCAAATCCTATAGTAACCCCTATCCATATTCAACCAGAATGATATTTTTTATTCGCATATGCAATTTTACGATCCATTCCTAATAAATTAGGAGGTGTGATTGCTTTATTATCATCAATTATTATCCTATATTTCTTACCTTTAATTAATCCTAAATTTAATTCATTCACATTTTATCCTATTAATCAAATTATATATTGAATTTTTTCTAATACATTTATTCTCTTAACTTGAGCAGGATCTCAAGTCATTGAATATCCATTTATTATTATTACCCAAATCCTATCATATATTTATTTTTTATACTTTATATTTTCTTACATCTGCTTAAAAATATGAGATAAAATAATTTTTTATTATAATTAAAATATATTAAAAATAAAATTAAACTTAAATTTATCACACTAATTTTTTTATTTAGTTAATGATCTTGATTAAAGTTTATGTTT"
newLine = 0
temp = ""
for i in range(0, len(fasta)):
    
    if i % 10 == 0 and i > 0:

        if newLine == 5:
            temp += fasta[i-10: i] + "\n\n"
            newLine = 0

        else:
            temp += fasta[i-10: i] + " "
            newLine += 1


fastaText = open("CBfasta_formica.txt", "w")
fastaText.write(temp)
fastaText.close()
